[package]
name = "postgres_range"
version = "0.9.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Range support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-range"
documentation = "https://sfackler.github.io/rust-postgres-range/doc/v0.9.0/postgres_range"

[dependencies]
time = "0.1"
postgres = "0.15"
postgres-protocol = "0.3"

[dev-dependencies]
postgres = { version = "0.15", features = ["with-time"] }