[package]
name = "postgres_range"
version = "0.1.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Range support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-range"
documentation = "https://sfackler.github.io/doc/postgres_range"

[dependencies]
postgres = "0.4"
time = "0.1"
