[package]
name = "postgres_range"
version = "0.6.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Range support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-range"
documentation = "https://sfackler.github.io/doc/postgres_range"

[dependencies]
time = "0.1"
postgres = "0.8"
byteorder = "0.3"

[dev-dependencies.postgres]
features = ["time"]
