[package]
name = "postgres_range"
version = "0.8.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Range support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-range"
documentation = "https://sfackler.github.io/rust-postgres-range/doc/v0.8.1/postgres_range"

[dependencies]
time = "0.1"
postgres = "0.11"
byteorder = ">= 0.3, < 0.5"

[dev-dependencies]
postgres = { version = "0.11", features = ["time"] }
